### PR TITLE
Update ESI for HubSpot, introduce TRACKING_HUBSPOT_ID

### PR DESCRIPTION
**Pull request by msbt**
## Summary of the changes / Why this is an improvement
This is part one of preventing #305 from happening again. I've also added the HubSpot tracking.

Can we test this on one repo first before pushing to all of them? The HubSpot tracking requires an environment variable to be set, can you take care of this, @amotl (pinging you on slack after this).

## Checklist

 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed

### CODE REVIEW

**Review by amotl — CHANGES_REQUESTED** [review]
[RTD build #15183589](https://readthedocs.org/projects/crate-docs-theme/builds/15183589/) croaked with `WARNING: unsupported theme option 'tracking_hubspot_id' given`.

You will probably have to add a section to `theme.conf`, similar to the section about the [segment.io tracking ID](https://github.com/crate/crate-docs-theme/blob/0.17.0/src/crate/theme/rtd/crate/theme.conf#L50-L52).

**Comment by msbt** [comment]
Thanks @amotl, I've adjusted the `theme.conf` and pushed an update, let me know if this works

**Review by amotl — APPROVED** [review]
> I've adjusted the `theme.conf` and pushed an update, let me know if this works.

Software tests signal success now, so I believe it will be good to go. Thank you! As a last task, maybe let's add an item to the changelog?

**Comment by msbt** [comment]
Hah, of course I forgot to save and push the changes, thanks, there you go @amotl!

**Pull request merged**
