### PR TITLE
Primary Navigation: Increase toctree.maxdepth to 4 for Cloud and Guides

### PR DESCRIPTION
**Pull request by amotl**
## Thoughts
A few sections may require more depth. Let's probe how this could make a difference for [Cloud](https://cratedb.com/docs/cloud/) and [Guides](https://cratedb.com/docs/guide/).

## Preview
Not much can be inspected by looking at the preview rendering of the `crate-docs-theme` project, because its docmentation doesn't provide any reasonable depth at all.

https://crate-docs-theme--515.org.readthedocs.build/en/515/

## References
Better previews and reviews are better conducted on behalf of relevant downstream projects.
- https://github.com/crate/cloud-docs/pull/79
- https://github.com/crate/cratedb-guide/pull/112

### CODE REVIEW

**Comment by matkuliak** [comment]
In general im for more depth. But in some examples it can be a bit confusing, at least to me. Like in [cratedb-guide#112](https://github.com/crate/cratedb-guide/pull/112) 
(https://cratedb-guide--112.org.readthedocs.build/performance/inserts/methods.html)

The additional items in primary navigation aren't pages but headers/titles. So it's showing the same thing as the right-hand menu, but then lacking the depth for h2 headers.

**Comment by amotl** [comment]
If the toctree would expand into pages instead of headers, I guess they would be displayed there. So, it gives what it advertises: More depth in general. How you design and shape it on the leaf node level is probably still up to the author.

**Comment by matkuliak** [comment]
Right, I know that it happening has nothing to do with this change. 

I meant this will, I think, lead to variant you mention first being more visible, which is unexpected to me if the menu is built primary to display links to pages.

**Comment by amotl** [comment]
It's really just a proposal to use at your disposal. I can easily just NOT adjust this setting for Cloud Docs.

> I meant this will, I think, lead to variant you mention first being more visible, which is unexpected to me if the menu is built primary to display links to pages.

I hear you, but in general, the primary navigation can be used for anything. It doesn't have to be "primarily built to navigate to pages". I mean, it all depends on the corresponding subtree at hand, and can be different from page to page.

**Comment by amotl** [comment]
What do you think, @proddata? I will apply maxdepth 4 to CrateDB Guide. Do you also want it for CrateDB Cloud Docs, or better not?

**Comment by amotl** [comment]
The relevant commit a750f880 has been included into GH-390, and will make it into the next release when there are no other objections about it.

**Pull request closed without merging**
