### PR TITLE
Navigation: Add header menu items from website

### PR DESCRIPTION
**Pull request by matkuliak**
## Summary of the changes / Why this is an improvement
We want to bring the top navigation from main page to the docs:
- Product
- Use cases
- Industries
- Resources 
- Pricing

## Preview
https://crate-docs-theme--534.org.readthedocs.build/en/534/

image

-----

cc @geragray

### CODE REVIEW

**Comment by matkuliak** [comment]
Hi @msbt, quick implementation of the navigation similar to our main site. I'm not really familiar with all the css in our docs, it's split into a couple of files so mostly made new classes. Let me know if I should shuffle some stuff elsewhere. Thanks!

**Comment by amotl** [comment]
Thanks. Isn't this supposed to go into some SSI snippet?

**Comment by matkuliak** [comment]
Not sure. After pushing, @msbt let me know about https://cratedb.com/_hcms/api/navi-header. That was previously used as a dynamic source for the list. So going to switch to that probably

**Comment by amotl** [comment]
Can you add this to https://cratedb.com/_hcms/api/navi-header instead, @msbt? 🙏

**Comment by msbt** [comment]
@amotl I'll give it a go, might take some time though

**Comment by msbt** [comment]
@amotl I've implemented the current navigation as fallback and reintroduced the esi's, are we happy with it? PR link is to the latest status (https://crate-docs-theme--534.org.readthedocs.build/en/534/)

**Review by amotl — APPROVED** [review]
Thanks. Please check, @geragray and/or @kneth. Thanks!

**Comment by amotl** [comment]
I guess it will be good to release, and applying "ack by timeout" will not cause too much harm, even it its duration was a bit short.

**Pull request merged**
