### PR TITLE
New glossary links styling

### PR DESCRIPTION
**Pull request by norosa**
this PR adds one commitc. the commit messages contain a description of the change

### CODE REVIEW

**Review by amotl — APPROVED** [review]

**Comment by norosa** [comment]
I will wait for @msbt to comment on my CSS changes. I am no expert! haha

**Comment by msbt** [comment]
@norosa the build doesn't work anymore, not sure if it's on my end, gonna check tomorrow:

```
ubuntu@dev:~/Documents/GitHub/crate-docs-theme/docs$ make SPHINX_OPTS='-W -n --host 0.0.0.0' dev
make[1]: Entering directory '/home/ubuntu/Documents/GitHub/crate-docs-theme/docs'
make[1]: Leaving directory '/home/ubuntu/Documents/GitHub/crate-docs-theme/docs'
make[1]: Entering directory '/home/ubuntu/Documents/GitHub/crate-docs-theme/docs'
Creating a Python virtual environment...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError
ERROR: Python>=3.7 is required.
.crate-docs/src/rules.mk:134: recipe for target '.crate-docs/.venv/bin/activate' failed
make[1]: *** [.crate-docs/.venv/bin/activate] Error 1
make[1]: Leaving directory '/home/ubuntu/Documents/GitHub/crate-docs-theme/docs'
Makefile:152: recipe for target 'dev' failed
make: *** [dev] Error 2
```
python --version gives Python 3.7.9

**Comment by norosa** [comment]
@msbt can you run `make reset` and then try again?

**Comment by norosa** [comment]
@amotl you added this check. do you know what's up here? :)

**Comment by amotl** [comment]
> do you know what's up here? :)

Everything should work again after upgrading to crate-docs 1.0.0. Please integrate #246 and then #245 afterwards. After that, you might also want to bring in #247.

Thanks already!

**Comment by norosa** [comment]
@amotl I removed my build commit. I also removed the links in `docs/index.rst` (that you recently modified) because neither of those links are actually used in the doc

**Comment by amotl** [comment]
Hi Naomi,

[1] croaks on:

> /home/runner/work/crate-docs-theme/crate-docs-theme/docs/index.rst:23:Unknown target name: "report an issue".

[2] also mentions that as warnings, but apparently doesn't croak. However, we can see it is still running on Sphinx 1.8.5.

Apart from that, from recognizing the difference between the linkchecker output between [1] and [2], I wonder if we already use the `--keep-going` flag to `sphinx-build` here?

With kind regards,
Andreas.

[1] https://github.com/crate/crate-docs-theme/pull/245/checks?check_run_id=2139729762#step:4:136
[2] https://readthedocs.org/projects/crate-docs-theme/builds/13279104/

**Comment by amotl** [comment]
> I wonder if we already use the --keep-going flag to sphinx-build here or there?

https://github.com/crate/crate-docs/pull/66 brings it back to `crate-docs`. Can you issue a 1.0.1 fixup release?

**Comment by norosa** [comment]
@amotl can I ask you to fix the `index.rst` error? for some reason, I cannot rebase against `origin/master` in my local checkout.  I think I borked my local git refs somehow as I get multiple `warning: refname 'origin/master' is ambiguous` messages

I will try to fix my git but it's probably faster for you to just add the link ref back in yourself and squash

also perhaps you can do the crate-docs 1.0.1 release? I don't trust my local checkouts as I seem to have borked the crate-docs history too (leading to the two recent `master` history issues)

I will just wipe my clones and start afresh

**Comment by msbt** [comment]
Ok this is somewhat embarassing, I had python3 installed two times and one of those was 3.6.9, so the make script got stuck there. Either way, thanks to @amotl I've an updated Ubuntu 20 now which has a default python 2 and 3 installed and the master build works. The PR however doesn't, only when I remove the links in `index.rst` (\`report an issue\`_ and \`developer guide\`_ because they have no target).

Other than that, glossary looks fine!

**Comment by norosa** [comment]
@msbt thanks! yeah for some reason, those links were added on master but I haven't been able to pick up that change so my removal breaks things

I'll try again now to fix this

**Comment by norosa** [comment]
fixed it :)

**Comment by amotl** [comment]
Yay, merged. Sorry, just came back to the keyboard.

**Pull request merged**
