### PR TITLE
improve top level docs

### PR DESCRIPTION
**Pull request by nslater**

### CODE REVIEW

**Comment by nslater** [comment]
@chaudum I have three specific questions here:

1) is the text under this heading correct:

https://github.com/crate/crate-docs-theme/tree/nomi/top-level-docs#configuration

2) is the text about Grunt correct:

https://github.com/crate/crate-docs-theme/blob/nomi/top-level-docs/DEVELOP.rst#setup

3) is it okay to warn about Grunt being obsolete here, or should this PR (or another PR that goes along with it) also remove Grunt? (I an not familiar with Grunt so I am not immediately clear on what would need to be changed)

**Comment by chaudum** [comment]
@nslater 
1. yes, is correct
2. and 3. instead of "warning" people here about things not working. we should jut get rid of it

**Comment by chaudum** [comment]
as it seems `bin/grunt watch` does not do anything, because there are no `.less` files any more

**Comment by chaudum** [comment]
`bin/grunt watch` just builds the documention automatically when html files change

**Pull request merged**
