### PR TITLE
NG: Theme modernization, last mile

### PR DESCRIPTION
**Pull request by amotl**
## About
Improvements for the big modernization patch, submitted by @msbt. Thanks!

- GH-390

## Preview
https://crate-docs-theme--506.org.readthedocs.build/en/506/

### CODE REVIEW

**Comment by amotl** [comment]
Thank you very much for adding so much progress to this. Hereby, I am starting a small collection of backlog items. Some of them might be unrelated to the modernization, some indeed are.

- [ ] Citations should not increase font size.
       Example: https://crate-docs-theme--506.org.readthedocs.build/en/506/links.html#introduction

- [ ] We are using "table of content" elements heavily, so we will need to remove that admonition of Furo.
       Example: https://crate-docs-theme--506.org.readthedocs.build/en/506/links.html#examples

**Comment by msbt** [comment]
fixed bigger quote text via https://github.com/crate/crate-docs-theme/pull/506/commits/786fd2ae8a5cf7609deba64002c11e91aeb99ae4 (apparently that also happened on the current docs, but I couldn't find an example)

**Comment by msbt** [comment]
@amotl the ToC error is "fixed" with https://github.com/crate/crate-docs-theme/pull/506/commits/08586b7a03e1d3bf231141f60a1a23f3e1ea5305

Pages with code snippets or other content that's wider than the screen don't screw up the layout anymore, had to give up fluid containers for that, but we'll survive without ;)

I did however find a strange 404 which tries to load a css asset from `/_static/` (without a filename), unsure where that comes from or what it is.

Other than that: Algolia instantsearch is included now, but needs some more live to get the URL right (i.e. it points to
`https://crate-docs-theme--506.org.readthedocs.build/search.html?q=joins` instead of
`https://crate-docs-theme--506.org.readthedocs.build/en/506/search.html?q=joins`

Honorable mentions: left sidebar has a grey background now and should always be boxed and not overflow at the bottom. With that fixed, I gave the menu items 2px more padding for easier navigation and better UX. Search button is square again to fit in with the other elements. Also added and finetuned a few breakpoints for when the sidebars and header disappear.

**Comment by amotl** [comment]
Hi. I love the appearance as seen on the [preview](https://crate-docs-theme--506.org.readthedocs.build/en/506/) now. Thanks a stack for working on this and bringing it to this level. 🌻 

One final things comes to mind: What about slotting in the SEARCH button into a different location instead? When possible, let's also hear about voices from others. Thanks!

/cc @seut, @matriv, @matkuliak, @proddata, @ckurze, @geragray

**Comment by proddata** [comment]
Looks great 👍 
a few suggestions:
image

**Comment by msbt** [comment]
@proddata I had the search in the left sidebar once already, but this means on mobile it will only be visible when the sidebar is open (or we duplicate the field and show it somewhere else when it disappears).

I was also playing around with the position of the version chooser and it didn't look great when it wasn't aligned with the top nav. However, if we lose it, that shouldn't be a problem anymore. Should we keep Login/Get CrateDB or drop them as well?

Btw, can you do a hard refresh? No idea where some of those background colors are coming from in your screenshot, I don't see that bar on the right ;)

**Comment by proddata** [comment]
> @proddata I had the search in the left sidebar once already, but this means on mobile it will only be visible when the sidebar is open (or we duplicate the field and show it somewhere else when it disappears).

Considering that searching is going away from the page anyway I would consider it fine. 
I think the sidebar(s) have a much bigger issue on mobile devices in the sense that the font ins tiny ;) 

> Should we keep Login/Get CrateDB or drop them as well?

We might want to keep  "Login" and "Get CrateDB" and add a button back to the homepage?

> Btw, can you do a hard refresh? No idea where some of those background colors are coming from in your screenshot, I don't see that bar on the right ;)

Are you using an external mouse or a device with just a touchpad?
It is a scrollbar. If that is not shown, the version picker is less of a problem

image

**Comment by msbt** [comment]
@proddata pushed another bunch of updates, is that better? I left community in there too, looks a bit empty otherwise ;)

As for the scrollbar: laptop and external mouse/keyboard, so no touch-only device. Either way, moved things around, did that fix the problem?

**Comment by amotl** [comment]
> One final things comes to mind: What about slotting in the SEARCH button into a different location instead?

Thank you very much for your recent changes. Perfect! 🌻

**Comment by proddata** [comment]
> As for the scrollbar: laptop and external mouse/keyboard, so no touch-only device. Either way, moved things around, did that fix the problem?

I think it is Chrome / Firefox specific

**Comment by proddata** [comment]
Looks good now 👍

**Review by amotl — COMMENTED** [review]
Thanks for this patch, @msbt. We will integrate the improvements into GH-390, and run a devX release, in order to be able to slap the new theme on a few downstream projects.

**Pull request merged**
