### PR TITLE
Matthias/admonitions reloaded

### PR DESCRIPTION
**Pull request by msbt**
## Summary of the changes / Why this is an improvement

As discussed [here](https://github.com/crate/crate-docs-theme/issues/221), this should improve readability/visbility of admonitions in the docs pages.

## Checklist

 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed

### CODE REVIEW

**Review by mechanomi — APPROVED** [review]

**Comment by mechanomi** [comment]
please squash your changes before rebasing

let me know when you'd like me to release a new version of the theme, etc.

**Comment by msbt** [comment]
thanks @mechanomi, sorry for not squashing! yes please, release a new version and push to some repos to check out if the new layout works properly.

**Comment by mechanomi** [comment]
0.10.17 released

**Comment by mechanomi** [comment]
docs rebuilding

**Comment by msbt** [comment]
thanks, appreciate it, looking good so far, right?

**Pull request merged**
