### PR TITLE
Improve bundling of custom JavaScript and CSS assets

### LINKED ISSUE #241: CSS minification should be handled by the build system
https://github.com/crate/crate-docs-theme/commit/02bcb186bce9a9e6f1de356a9f84dc0e7a582204 introduced CSS minification. however, it looks like @msbt minified the CSS by hand. the result is that if you edit the source CSS files, your changes will not have any effect. the theme only reads the minified CSS and ignores the source CSS (which is working as intended)

we need a way of developing the CSS that doesn't require you to minify the CSS by hand every time you make a change. people who know you have to do this are likely to forget occasionally. and people who don't know this are likely to be confused about why their changes are not showing up

I am not sure what CSS minification tool @msbt used. we need to identify what tool to use before we can implement a build rule for doing this

I am guessing that the command to minify the CSS ought to be added after: https://github.com/crate/crate-docs-theme/blob/59905a67e9b064641c1ee5058b10b5f8fab8a846/Makefile#L60

and before: https://github.com/crate/crate-docs-theme/blob/59905a67e9b064641c1ee5058b10b5f8fab8a846/Makefile#L61

no other changes ought to be necessary. the `Makefile` in `docs` uses the `crate-docs-theme` package that is built in the parent directory, so any changes made to that package will show up when you view the test docs (as long as a `make reset` is run every time changes are made, to clear the local Python package cache).

---

this issue came up while working on https://github.com/crate/tech-writing-domain/issues/382

as an interim workaround, I plan to fix the CSS issue I am working on and generate a new minified CSS by hand and check it into the repository to replace the existing one

### PR DESCRIPTION
**Pull request by amotl**
Hi there,

this patch removes assets which have been inlined into this repository before and replaces them by a bundling system based on yarn and webpack. It will resolve #241.

With kind regards,
Andreas.

### CODE REVIEW

**Comment by norosa** [comment]
will let @msbt review this one :)

**Comment by msbt** [comment]
I've tried that build and it works fine! All I had to do was
```
sudo apt update
curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
sudo apt-get install -y nodejs
sudo npm install --global yarn
```
beforehand, then it ran through as expected, nice work @amotl!

**Comment by amotl** [comment]
> I've tried that build and it works fine! All I had to do was [install Node.js and yarn].

Thank you. I've added respective instructions through 8d9af3add.

**Comment by amotl** [comment]
I also removed Fontawesome completely through 4b37ec0673.

**Review by msbt — APPROVED** [review]
looking good!

**Pull request merged**
