### PR TITLE
New rating feature for docs & many updates and hopefully improvements

### PR DESCRIPTION
**Pull request by msbt**
## Summary of the changes / Why this is an improvement

Made a lot of changes because our lighthouse rating is not great. This will bring everything in the 90+ region (at least it did locally). One major addition is a "rate this page" feature requested by Wolfang and the customer success folks.

- SEO: Added `rel="noopener"` to Github links (Links to cross-origin destinations are unsafe)
- Updated/removed Bootstrap and jQuery packages (9 vulnerabilities detected)
- SEO: Added `height: auto;` to the logo css (lighthouse complained because of a wrong AR)
- SEO: Added alt & title tags to logos in header and footer
- Moved esi to the correct position
- SEO: Added dns-prefech/preconnect to googleapis.com and cdn.crate.io
- Updated version tag for css/js in `base.html` for cleaner caches
- SEO: Added language `xml:lang="en" lang="en"`
- Added Favicon
- SEO: Preloading Font
- SEO: Minified/Combined static js/css files (except custom and doctools)
- SEO: Removed `maximum-scale=1` from meta viewport to allow zooming
- Added new rating feature below the feedbackbox
- SEO: Changed h3 to h2 for feedbackbox and new rating
- Fixed a minor css error in `crateio.css` and added `font-display: swap;`
- Fixed colors of the `Toggle Doc Menu` (mobile)

Since I removed Bootstrap and only copied over the necessary elements for rows and columns, some things might not look great, that's why I would suggest a beta release (like we did with ESI) which will be pushed to a single repo, if this works out, roll it out on all docs.

## Checklist

 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed

### CODE REVIEW

**Comment by mechanomi** [comment]
@msbt nice work!!!! thanks so much!

re the theme version number problem you were having, I think I fixed it. check out https://github.com/crate/crate-docs-theme/pull/238/commits/811fba45816362a0341c65dd4311d630015e984a and https://github.com/crate/crate-docs-theme/pull/238/commits/c8e40dcb5894afc9f590b632aac3a0e500e5c67e

you can use `{{ theme_ver }}` anywhere you want in the templates now

it will produce lines like this:

```
<script type="text/javascript" src="_static/js/script.min.js?ver=0.12.0"></script>
```

**Review by mechanomi — COMMENTED** [review]
I think the "Rate this page" feature is an excellent addition. however, to my eyes, the bottom of the pages look cluttered now

here's my suggestion:

- drop the "Rate this page" header itself
- move the rating box up so it comes right after the existing "Feedback" header but before the GitHub box

I suggest this because rating the page is a kind of feedback, and I think having two headings at the bottom of every page is probably too much

what do you think? I'd take a go at it myself but I'm not a designer and there's probably some additional changes needed to make it look right haha

I am not even sure if we should keep the two boxed areas seperate. maybe there's a way to integrate them. it just seems to me that moving the rating box up is the easiest fix

lemme know what you think!

**Comment by msbt** [comment]
Thanks a lot for the version fix, that's exactly what I wanted!

I'll talk to @belringer about the rating layout, since he's the one in charge of design. But at a first glance, removing the title and moving the box up does not work 100% because of the New issue/Edit on GitHub links (images are a bit stretched, my vms resolution is a bit off):
grafik

Leaving it below and removing the title could be an option:
grafik

Or if we remove the Feedback headline from its container, we could do it like this:
grafik

But again, lets wait for Andreas' feedback, he'll know what to do.

**Comment by belringer** [comment]
Then I would change the position of the GitHub buttons:
image
or
image

**Comment by msbt** [comment]
nice, thanks @belringer, I would go with the first one, so more people will see the rating stuff, but I'll wait for @mechanomi and let her decide

**Comment by matthijskrul** [comment]
I agree, I think the first one is better - it also imho looks nicer to ask for a general impression first before showing existing issues

**Comment by infoverload** [comment]
I also vote for the first one

**Comment by msbt** [comment]
While we're at it: Can a readthedocs admin disable the Google Analytics tracking? I reckon that a lot of our users are privacy focused and there's still the rtd Google tracking enabled (https://github.com/readthedocs/readthedocs.org/pull/7175 / https://docs.readthedocs.io/en/stable/guides/google-analytics.html#disabling-google-analytics-on-your-project). It should be no problem to deactivate it, since our own solution is implemented via segment and since we're rebuilding them anyways, this would be a good time to disable it.

**Comment by msbt** [comment]
ok since version 1 got good feedback, I already moved it around, please test and let me know if it's good to go

**Comment by mechanomi** [comment]
I agree with version 1! excellent stuff!!

just built the docs locally to test

is this expected behavior after you submit a rating:

1. the page refreshes (with a visible white flash of no content)
2. the rating box looks exactly the same as it did before I submitted a rating

comments:

- for (1) I was expecting it to be handled with some sort of ajax request
- for (2) I was expecting either a "Thank you" message or for the rating I chose to "stick" (so it would show 4 stars instead of 0, for example)

**Comment by msbt** [comment]
> is this expected behavior after you submit a rating:
> 
>     1. the page refreshes (with a visible white flash of no content)
> 
>     2. the rating box looks exactly the same as it did before I submitted a rating

Uh no, that's weird, it's supposed to say "Thank you for your feedback!" and the submit button should disappear. My local instance worked in both, Firefox and Chromium. Is your custom.js up to date?

**Comment by mechanomi** [comment]
@msbt weird. I tested again and it works as expected

one thing comes to mind: if you refresh the page it resets the status. I guess we could save the state to localstorage so when you visit the page again you will see you already rated it (for as long as you don't reset localstorage). but I am not sure how much effort this is and whether it is worth it. thoughts?

if localstorage is not worth it, then I think we can merge this PR and get a new release of the theme out for testing immediately

**Comment by msbt** [comment]
@mechanomi generally I agree with you, the localstorage feature sounds great, but I reckon this is something for v2. I would want to see if people are going to use it before putting in more time for such enhancements. I would definitely keep that in mind and add it in the future if it's getting traction. So if it's ok with you, I would go for a merge and test on a live repo (as mentioned, since I've removed a lot of js/css, there might be some minor issues).

**Comment by msbt** [comment]
@mechanomi I've migrated the changes from #237 to this branch, please give it another rebuild to see if that's what you wanted

**Review by mechanomi — APPROVED** [review]

**Comment by mechanomi** [comment]
disabled GA on all docs projects now (via the RTD interface), as requested!

**Comment by mechanomi** [comment]
incremental roll-out in progress

**Pull request merged**
